---
- name: install mysql repository
  yum:
    name: "{{ MY_PACKAGE_RPM }}"
  tags: mysql

- name: "detected {{ MY_PACKAGE_ENABLE }} status"
  shell: "mysqld --version | grep {{ MY_VERSION }}"
  register: mysql_status
  failed_when: no
  check_mode: no
  changed_when: mysql_status.rc != 0
  tags: mysql

- name: install mysql package
  yum:
    enablerepo: "{{ MY_PACKAGE_ENABLE }}-community"
    disablerepo: "{{ MY_PACKAGE_DISABLE }}-community"
    name:
      - MySQL-python
      - mysql-community-server
  tags: mysql

- name: copy mysql conf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
    mode: 0600
  notify: restart mysql service
  tags: mysql

- name: setup network conf
  shell: echo "NETWORKING=yes" > /etc/sysconfig/network
  args:
    creates: /etc/sysconfig/network
  check_mode: no
  tags: mysql

- name: start mysql service
  service:
    name: mysqld
    state: started
    enabled: yes
  tags: mysql

- name: change the root password
  command: >
    mysqladmin password '{{ mysql_user.password }}' -u root
  when: mysql_status is changed
  notify: restart mysql service
  tags: mysql

- include_tasks: replication.yml
  when: mysql_replication
  tags: mysql-replication
