---
- name: create replication user to master
  mysql_user:
    login_user: "{{ mysql_user.name }}"
    login_password: "{{ mysql_user.password }}"
    name: "{{ mysql_replication_user.name }}"
    host: "{{ mysql_replication_slave | default('%') }}"
    password: "{{ mysql_replication_user.password }}"
    priv: '*.*:REPLICATION SLAVE,REPLICATION CLIENT'
    state: present
  when: mysql_replication_role == 'master'
  tags: mysql-replication

- name: get replication slave status to slave
  mysql_replication:
    mode: getslave
    login_user: "{{ mysql_user.name }}"
    login_password: "{{ mysql_user.password }}"
  register: slave
  when: mysql_replication_role == 'slave'
  tags: mysql-replication

- name: change replication master to slave
  mysql_replication:
    mode: changemaster
    login_user: "{{ mysql_user.name }}"
    login_password: "{{ mysql_user.password }}"
    master_host: "{{ mysql_replication_master }}"
    master_port: "{{ mysql_listen_port }}"
    master_user: "{{ mysql_replication_user.name }}"
    master_password: "{{ mysql_replication_user.password }}"
    master_auto_position: 1
  when: >
    mysql_replication_role == 'slave'
    and slave.Is_Slave is defined and not slave.Is_Slave
  tags: mysql-replication

- name: start replication to slave
  mysql_replication:
    mode: startslave
    login_user: "{{ mysql_user.name }}"
    login_password: "{{ mysql_user.password }}"
  when: >
    mysql_replication_role == 'slave'
    and slave.Is_Slave is defined and not slave.Is_Slave
  tags: mysql-replication
