---
- name: Converge
  hosts: all
  pre_tasks:
    - name: get host ip
      local_action: shell docker inspect --format \{\{.NetworkSettings.IPAddress\}\} instance-1
      register: instance_ip
      changed_when: false
      check_mode: no
    - name: set fact
      set_fact:
        mysql_replication_master: "{{ instance_ip.stdout }}"
      changed_when: false
      check_mode: no
  roles:
    - role: ../../../
